### ISSUE TITLE
Composer fails RuntimeException Could not delete

### ISSUE THREAD

**Issue by ryanburnette** [xyu/heroku-wp#161]
I am now getting this error anytime I attempt to run `composer update` in vagrant. This happens in all my projects, including a fresh clone of this project and `vagrant up`.

```
    herokuwp: Plugin installation failed, rolling back
    herokuwp:   - Removing composer/installers (v1.7.0)
    herokuwp:                                                                   
    herokuwp:   [RuntimeException]                                              
    herokuwp:   Could not delete /app/vendor/composer/installers/src/Composer:  
```

```
macOS 10.14.6 (18G103)
Virtualbox 6.0.12r133076
Vagrant 2.2.5
```

[This](https://github.com/drupal-composer/drupal-project/issues/241#issuecomment-292151320) could be related.
