### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by janoist1** [xyu/heroku-wp#176]
I'm trying to run the project locally but I get "File not found" when accessing it through browser.

I got the following error message when first run `vagrant up`:

```
    herokuwp: Setting up unzip (6.0-20ubuntu1) ...
    herokuwp: 1024+0 records in
    herokuwp: 1024+0 records out
    herokuwp: 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.18568 s, 906 MB/s
    herokuwp: Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
    herokuwp: no label, UUID=83a83a06-6cce-47a5-9d1f-781e648a8c87
    herokuwp: The "wp-cli/autoload-splitter" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
    herokuwp: The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
    herokuwp: PHP Fatal error:  Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /app/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11
    herokuwp: 
    herokuwp: Fatal error: Class UpdateHelper\ComposerPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /app/vendor/kylekatarnls/update-helper/src/UpdateHelper/ComposerPlugin.php on line 11
    herokuwp: Restarting php7.0-fpm (via systemctl): php7.0-fpm.service
    herokuwp: .
    herokuwp: Restarting nginx (via systemctl): nginx.service
    herokuwp: .
```

Update:

SSH into vagrant and run bin/composer update inside it gives me the following error:
```
...
  - Removing composer/ca-bundle (1.2.6)
  - Removing composer/composer (1.9.3)
  - Updating kylekatarnls/update-helper (1.2.0 => 1.2.1): Downloading (100%)         
  - Updating composer/installers (v1.8.0 => v1.9.0): Downloading (100%)         

                                                                                           
  [ErrorException]                                                                         
  copy(/app/vendor/WordPress/WordPress): failed to open stream: No such file or directory  
                                                                                           
```
